### ISSUE TITLE
带有标点符号时无法成功翻译，希望能直接翻译一句话，感谢大佬👍

### ISSUE THREAD

**Issue by ocean1798** [qyjandroid/zh-translate-en#1]

**Comment by qyjandroid** [comment]
> _No description provided._

你是想快速将一句话英文翻译为中文是吧

**Comment by ocean1798** [comment]
> > _没有提供描述。_
> 
> 你想快速说出一句话英文翻译为中文是吧

对👍

**Comment by qyjandroid** [comment]
> > > _没有提供描述。_
> > 
> > 
> > 你想快速说出一句话英文翻译为中文是吧
> 
> 对👍

好的，我抽空看看给支持一下。

**Comment by ocean1798** [comment]
> > > > _没有提供描述。_
> > > 
> > > 
> > > 你想快速地说出一句话英文翻译成中文是吧
> > 
> > 
> > 对👍
> 
> 好的，我抽空给支持一下。

主要是中译英，能互译是最好的👍，感谢大佬

**Comment by qyjandroid** [comment]
> > > > > _没有提供描述。_
> > > > 
> > > > 
> > > > 你想快速地说出一句话英文翻译成中文是吧
> > > 
> > > 
> > > 对👍
> > 
> > 
> > 好的，我抽空给支持一下。
> 
> 主要是中译英，能互译是最好的👍，感谢大佬

插件：0.2.2版本已支持，可以选中你需要翻译的英文句子，然后右键-》英转中并复制到粘贴板

**Comment by ocean1798** [comment]
> > > > > > _没有提供描述。_
> > > > > 
> > > > > 
> > > > > 你想快速地说出一句话英文翻译成中文是吧
> > > > 
> > > > 
> > > > 对👍
> > > 
> > > 
> > > 好的，我抽空给支持一下。
> > 
> > 
> > 主要是中译英，能互译是最好的👍，感谢大佬
> 
> 插件：0.2.2版本已支持，可以选中你需要翻译的英文句子，然后右键-》英转中并复制到粘贴板

👍👍👍感谢大佬
